# Generated by Django 3.0.6 on 2020-06-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200601_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='logo_carre_VF.png', upload_to='category-img/'),
        ),
    ]
