# Generated by Django 3.0.6 on 2020-06-09 07:57

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200608_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(null=True, upload_to='title-img/'),
        ),
    ]
